FROM docker.io/library/golang:1.22-bookworm AS build
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=1 go build -trimpath -o /out/portfolio .
FROM docker.io/library/debian:bookworm-slim
WORKDIR /app
COPY --from=build /out/portfolio /app/portfolio
COPY static /app/static
COPY components/*.txt /app/github.com/midasvanveen/portfolio/v2/components/
ENV PORT=:4000
EXPOSE 4000
ENTRYPOINT ["/app/portfolio"]
